# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tsoj/Dokumente/Projects/glome_public

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tsoj/Dokumente/Projects/glome_public

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tsoj/Dokumente/Projects/glome_public/CMakeFiles /home/tsoj/Dokumente/Projects/glome_public/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tsoj/Dokumente/Projects/glome_public/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glome

# Build rule for target.
glome: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glome
.PHONY : glome

# fast build rule for target.
glome/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/build
.PHONY : glome/fast

src/Renderer.o: src/Renderer.cpp.o

.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i

.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s

.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Window.o: src/Window.cpp.o

.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i

.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s

.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

src/World.o: src/World.cpp.o

.PHONY : src/World.o

# target to build an object file
src/World.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/World.cpp.o
.PHONY : src/World.cpp.o

src/World.i: src/World.cpp.i

.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s

.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

src/gl.o: src/gl.cpp.o

.PHONY : src/gl.o

# target to build an object file
src/gl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/gl.cpp.o
.PHONY : src/gl.cpp.o

src/gl.i: src/gl.cpp.i

.PHONY : src/gl.i

# target to preprocess a source file
src/gl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/gl.cpp.i
.PHONY : src/gl.cpp.i

src/gl.s: src/gl.cpp.s

.PHONY : src/gl.s

# target to generate assembly for a file
src/gl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/gl.cpp.s
.PHONY : src/gl.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/obj.o: src/obj.cpp.o

.PHONY : src/obj.o

# target to build an object file
src/obj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/obj.cpp.o
.PHONY : src/obj.cpp.o

src/obj.i: src/obj.cpp.i

.PHONY : src/obj.i

# target to preprocess a source file
src/obj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/obj.cpp.i
.PHONY : src/obj.cpp.i

src/obj.s: src/obj.cpp.s

.PHONY : src/obj.s

# target to generate assembly for a file
src/obj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/obj.cpp.s
.PHONY : src/obj.cpp.s

src/types.o: src/types.cpp.o

.PHONY : src/types.o

# target to build an object file
src/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/types.cpp.o
.PHONY : src/types.cpp.o

src/types.i: src/types.cpp.i

.PHONY : src/types.i

# target to preprocess a source file
src/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/types.cpp.i
.PHONY : src/types.cpp.i

src/types.s: src/types.cpp.s

.PHONY : src/types.s

# target to generate assembly for a file
src/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/types.cpp.s
.PHONY : src/types.cpp.s

src/utility.o: src/utility.cpp.o

.PHONY : src/utility.o

# target to build an object file
src/utility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/utility.cpp.o
.PHONY : src/utility.cpp.o

src/utility.i: src/utility.cpp.i

.PHONY : src/utility.i

# target to preprocess a source file
src/utility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/utility.cpp.i
.PHONY : src/utility.cpp.i

src/utility.s: src/utility.cpp.s

.PHONY : src/utility.s

# target to generate assembly for a file
src/utility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glome.dir/build.make CMakeFiles/glome.dir/src/utility.cpp.s
.PHONY : src/utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... glome"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/World.o"
	@echo "... src/World.i"
	@echo "... src/World.s"
	@echo "... src/gl.o"
	@echo "... src/gl.i"
	@echo "... src/gl.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/obj.o"
	@echo "... src/obj.i"
	@echo "... src/obj.s"
	@echo "... src/types.o"
	@echo "... src/types.i"
	@echo "... src/types.s"
	@echo "... src/utility.o"
	@echo "... src/utility.i"
	@echo "... src/utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

